In [48]:
import pandas as pd

df = pd.read_csv("http://114.207.245.181:13000/csv/Mobile_price.csv")
df.head(1)

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1

In [49]:
t1 = {'battery_power':'베터리용량', 'blue':'블루투스지원여부', 'clock_speed':'CPU클럭속도',
      'dual_sim':'듀얼SIM지원여부', 'fc':'전면카메라화소수', 'four_g':'4G지원여부',
       'int_memory':'내장메모리용량', 'm_dep':'휴대폰두께', 'mobile_wt':'휴대폰무게',
       'n_cores':'CPU코어수', 'pc':'후면카메라화소수', 'px_height':'화면해상도높이',
       'px_width':'화면해상도넓이', 'ram':'RAM용량', 'sc_h':'화면높이', 'sc_w':'화면넓이',
       'talk_time':'통화가능시간', 'three_g':'3G지원여부', 'touch_screen':'터치스크린지원여부',
       'wifi':'WIFI지원여부', 'price_range':'가격등급'
}

df.rename(columns=t1, inplace=True)
df.columns

Index(['베터리용량', '블루투스지원여부', 'CPU클럭속도', '듀얼SIM지원여부', '전면카메라화소수', '4G지원여부',
       '내장메모리용량', '휴대폰두께', '휴대폰무게', 'CPU코어수', '후면카메라화소수', '화면해상도높이', '화면해상도넓이',
       'RAM용량', '화면높이', '화면넓이', '통화가능시간', '3G지원여부', '터치스크린지원여부', 'WIFI지원여부',
       '가격등급'],
      dtype='object')

In [29]:
#import pandas as pd
#
#df1 = pd.get_dummies(
#    df, columns=['블루투스지원여부', '듀얼SIM지원여부', '4G지원여부', '3G지원여부', '터치스크린지원여부', 'WIFI지원여부'],
#    drop_first=True,
#    dtype=int
#)
#df1.head()

In [51]:
x = df.drop(columns=['가격등급', '화면해상도높이', '화면넓이'])
y = df['가격등급']

x.shape, y.shape

((2000, 18), (2000,))

In [45]:
# 데이터 분할
#from sklearn.model_selection import train_test_split
#
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
#x_train.shape, x_test.shape, y_train.shape, y_test.shape

In [32]:
# 스케일러
#from sklearn.preprocessing import StandardScaler
#
#scaler = StandardScaler()
#
#x_train_scaled = scaler.fit_transform(x_train)
#x_test_scaled = scaler.transform(x_test)
#
#x_train_scaled.shape, x_test_scaled.shape

In [33]:
#from tensorflow import keras
#from tensorflow.keras.layers import Input, Dense, Dropout
#
#model = keras.Sequential([
#    Input(shape=(18,)),
#    Dense(units=128, activation='relu'),
#    Dropout(0.2),
#    Dense(units=64, activation='relu'),
#    Dense(units=32, activation='relu'),
#    Dense(units=16, activation='relu'),
#    Dense(units=4, activation='softmax'),
#])
#
#model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
#model.summary()

In [34]:
#model.fit(x_train_scaled, y_train, epochs=2000, validation_split=0.2)

In [35]:
#model.evaluate(x_train_scaled, y_train), model.evaluate(x_test_scaled, y_test)

In [46]:
#from sklearn.ensemble import RandomForestClassifier
#from sklearn.metrics import accuracy_score
#
#model = RandomForestClassifier(
#    n_estimators=300, random_state=123, max_depth=10, min_samples_leaf=3, min_samples_split=12
#)
#model.fit(x_train, y_train)
#model.score(x_train, y_train), model.score(x_test, y_test)

In [52]:
importance_df = pd.DataFrame({
    "변수명": x.columns,
    "중요도": model.feature_importances_
})

importance_df = importance_df.sort_values(by="중요도", ascending=False)
importance_df

          변수명       중요도
12      RAM용량  0.630607
0       베터리용량  0.076172
11    화면해상도넓이  0.064242
8       휴대폰무게  0.033425
6     내장메모리용량  0.031255
14     통화가능시간  0.023817
10   후면카메라화소수  0.022049
2     CPU클럭속도  0.021099
13       화면높이  0.019577
4    전면카메라화소수  0.018029
7       휴대폰두께  0.017776
9      CPU코어수  0.016529
16  터치스크린지원여부  0.005143
3   듀얼SIM지원여부  0.004931
1    블루투스지원여부  0.004087
5      4G지원여부  0.004048
17   WIFI지원여부  0.003921
15     3G지원여부  0.003294

In [53]:
top_features = importance_df.head(10)["변수명"].tolist()
top_features

['RAM용량',
 '베터리용량',
 '화면해상도넓이',
 '휴대폰무게',
 '내장메모리용량',
 '통화가능시간',
 '후면카메라화소수',
 'CPU클럭속도',
 '화면높이',
 '전면카메라화소수']

In [54]:
x = df[top_features]
y = df['가격등급']
x.shape, y.shape

((2000, 10), (2000,))

In [55]:
# 데이터 분할
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1600, 10), (400, 10), (1600,), (400,))

In [58]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [59]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train_scaled, y_train)
svc.score(x_train_scaled, y_train), svc.score(x_test_scaled, y_test)

(0.945625, 0.905)

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    ''
}