In [43]:
import pandas as pd

df = pd.read_csv("http://114.207.245.181:13000/csv/Rossmann_Store_Sales.csv", low_memory=False)
df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [44]:
df.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

In [45]:
t1 = {'Store':'매장', 'DayOfWeek':'요일', 'Date':'날짜',
      'Sales':'매출', 'Customers':'고객수', 'Open':'영업유무',
      'Promo':'프로모션', 'StateHoliday':'공휴일', 'SchoolHoliday':'학교방학'}

df = df.rename(columns=t1)
df.columns

Index(['매장', '요일', '날짜', '매출', '고객수', '영업유무', '프로모션', '공휴일', '학교방학'], dtype='object')

In [46]:
# a => 일반 공휴일
# b => 부활절 휴일
# c => 성탄절
df['공휴일'].value_counts()

공휴일
0    986159
a     20260
b      6690
c      4100
Name: count, dtype: int64

In [47]:
df.dtypes

매장       int64
요일       int64
날짜      object
매출       int64
고객수      int64
영업유무     int64
프로모션     int64
공휴일     object
학교방학     int64
dtype: object

In [48]:
df['날짜'] = pd.to_datetime(df['날짜'])
df['년'] = df['날짜'].dt.year
df['월'] = df['날짜'].dt.month
df['일'] = df['날짜'].dt.day

df.dtypes

매장               int64
요일               int64
날짜      datetime64[ns]
매출               int64
고객수              int64
영업유무             int64
프로모션             int64
공휴일             object
학교방학             int64
년                int32
월                int32
일                int32
dtype: object

In [49]:
# 공휴일 one hot 으로 변경
df1 = pd.get_dummies(
    df,
    columns=['공휴일'],
    drop_first=True,
    dtype=int
)

df1.head(1)

,매장,요일,날짜,매출,고객수,영업유무,프로모션,학교방학,년,월,일,공휴일_a,공휴일_b,공휴일_c
0,1,5,2015-07-31,5263,555,1,1,1,2015,7,31,0,0,0

In [50]:
# 참고용 => 분포변경
import numpy as np
print("원본")
s = np.array([0, 100, 1000, 10000, 100000])
print(s)

print("분포변경")
g = np.log1p(s)     # log(1+x)
print(g)

print("원본")
r = np.expm1(g)
print(r)

원본
[     0    100   1000  10000 100000]
분포변경
[ 0.          4.61512052  6.90875478  9.21044037 11.51293546]
원본
[0.e+00 1.e+02 1.e+03 1.e+04 1.e+05]

In [51]:
y = np.log1p(df['매출']).values
x = df1.drop(columns=['날짜', '매출']).values
x.shape, y.shape

((1017209, 12), (1017209,))

In [52]:
# 데이터 분할
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((813767, 12), (203442, 12), (813767,), (203442,))

In [53]:
# 스케일러
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

x_train_scaled.shape, x_test_scaled.shape

((813767, 12), (203442, 12))

In [56]:
from xgboost import XGBRegressor
model = XGBRegressor(random_state=123)
model.fit(x_train_scaled, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [58]:
from sklearn.metrics import r2_score

y_pred = model.predict(x_test_scaled)
r2_score(y_test, y_pred)

0.9980789401062028

In [62]:
# 모델 생성, 컴파일, 훈련하기
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

model = keras.Sequential([
    # 입력층 & 첫 번째 은닉층: 데이터 특성(Feature) 개수를 자동으로 감지하도록 input_shape 설정
    Dense(128, activation="relu", input_shape=(x_train_scaled.shape[1],)),
    BatchNormalization(), # 학습을 안정화하고 속도를 높임
    Dropout(0.2),         # 과적합 방지

    # 두 번째 은닉층
    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.2),

    # 세 번째 은닉층
    Dense(32, activation="relu"),
    
    # 출력층: 매출 예측(연속형 수치 회귀)이므로 뉴런 수는 1개, 활성화 함수는 없음
    Dense(1, activation="linear")
])

model.summary()

c:\Users\pknukdt\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 12,801 (50.00 KB)

 Trainable params: 12,417 (48.50 KB)

 Non-trainable params: 384 (1.50 KB)

In [64]:
model.compile(optimizer="adam", loss="mse", metrics=["mae"])
model.fit(x_train_scaled, y_train, epochs=500, validation_data=(x_test_scaled, y_test), batch_size=256)

Epoch 1/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0340 - mae: 0.1345 - val_loss: 0.0339 - val_mae: 0.1281
Epoch 2/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.0338 - mae: 0.1337 - val_loss: 0.0330 - val_mae: 0.1328
Epoch 3/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.0336 - mae: 0.1333 - val_loss: 0.0309 - val_mae: 0.1275
Epoch 4/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.0335 - mae: 0.1331 - val_loss: 0.0339 - val_mae: 0.1294
Epoch 5/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0334 - mae: 0.1328 - val_loss: 0.0319 - val_mae: 0.1284
Epoch 6/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0331 - mae: 0.1325 - val_loss: 0.0468 - val_mae: 0.1301
Epoch 7/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0329 - mae: 0.1324 - val_loss: 0.0306 - val_mae: 0.1285
Epoch 8/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0330 - mae: 0.1323 - val_loss: 0.0331 - val_mae: 0.1331
Epoch 9/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0329 - mae: 0.1323 - val_loss: 0.0319 - val_mae: 0.1281
Epoch 10/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0328 - mae: 0.1320 - val_loss: 0.0364 - val_mae: 0.1285
Epoch 11/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0329 - mae: 0.1319 - val_loss: 0.0310 - val_mae: 0.1273
Epoch 12/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0327 - mae: 0.1319 - val_loss: 0.0319 - val_mae: 0.1284
Epoch 13/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0329 - mae: 0.1318 - val_loss: 0.0336 - val_mae: 0.1272
Epoch 14/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0328 - mae: 0.1319 - val_loss: 0.0322 - val_mae: 0.1285
Epoch 15/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0327 - mae: 0.1317 - val_loss: 0.0311 - val_mae: 0.1266
Epoch 16/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0325 - mae: 0.1314 - val_loss: 0.0326 - val_mae: 0.1282
Epoch 17/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0328 - mae: 0.1315 - val_loss: 0.0310 - val_mae: 0.1271
Epoch 18/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0326 - mae: 0.1313 - val_loss: 0.0312 - val_mae: 0.1288
Epoch 19/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0328 - mae: 0.1315 - val_loss: 0.0335 - val_mae: 0.1273
Epoch 20/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0325 - mae: 0.1312 - val_loss: 0.0316 - val_mae: 0.1287
Epoch 21/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0325 - mae: 0.1312 - val_loss: 0.0351 - val_mae: 0.1276
Epoch 22/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0326 - mae: 0.1313 - val_loss: 0.0318 - val_mae: 0.1268
Epoch 23/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0325 - mae: 0.1310 - val_loss: 0.0314 - val_mae: 0.1274
Epoch 24/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0327 - mae: 0.1311 - val_loss: 0.0304 - val_mae: 0.1271
Epoch 25/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0326 - mae: 0.1311 - val_loss: 0.0357 - val_mae: 0.1316
Epoch 26/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0325 - mae: 0.1310 - val_loss: 0.0314 - val_mae: 0.1294
Epoch 27/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0327 - mae: 0.1310 - val_loss: 0.0312 - val_mae: 0.1285
Epoch 28/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0326 - mae: 0.1310 - val_loss: 0.0310 - val_mae: 0.1265
Epoch 29/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0325 - mae: 0.1308 - val_loss: 0.0320 - val_mae: 0.1302
Epoch 30/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0326 - mae: 0.1310 - val_loss: 0.0316 - val_mae: 0.1277
Epoch 31/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0324 - mae: 0.1307 - val_loss: 0.0311 - val_mae: 0.1268
Epoch 32/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - loss: 0.0322 - mae: 0.1306 - val_loss: 0.0343 - val_mae: 0.1274
Epoch 33/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0323 - mae: 0.1306 - val_loss: 0.0317 - val_mae: 0.1277
Epoch 34/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0321 - mae: 0.1304 - val_loss: 0.0304 - val_mae: 0.1259
Epoch 35/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0323 - mae: 0.1306 - val_loss: 0.0304 - val_mae: 0.1269
Epoch 36/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0323 - mae: 0.1306 - val_loss: 0.0319 - val_mae: 0.1278
Epoch 37/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0322 - mae: 0.1307 - val_loss: 0.0326 - val_mae: 0.1275
Epoch 38/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0321 - mae: 0.1305 - val_loss: 0.0305 - val_mae: 0.1255
Epoch 39/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0324 - mae: 0.1306 - val_loss: 0.0309 - val_mae: 0.1274
Epoch 40/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0322 - mae: 0.1306 - val_loss: 0.0315 - val_mae: 0.1270
Epoch 41/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0322 - mae: 0.1305 - val_loss: 0.0329 - val_mae: 0.1268
Epoch 42/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0322 - mae: 0.1306 - val_loss: 0.0310 - val_mae: 0.1275
Epoch 43/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0321 - mae: 0.1304 - val_loss: 0.0304 - val_mae: 0.1271
Epoch 44/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0323 - mae: 0.1305 - val_loss: 0.0311 - val_mae: 0.1263
Epoch 45/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0323 - mae: 0.1306 - val_loss: 0.0402 - val_mae: 0.1275
Epoch 46/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0322 - mae: 0.1305 - val_loss: 0.0312 - val_mae: 0.1275
Epoch 47/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0321 - mae: 0.1305 - val_loss: 0.0314 - val_mae: 0.1290
Epoch 48/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0320 - mae: 0.1304 - val_loss: 0.0306 - val_mae: 0.1280
Epoch 49/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0320 - mae: 0.1303 - val_loss: 0.0306 - val_mae: 0.1264
Epoch 50/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0322 - mae: 0.1303 - val_loss: 0.0308 - val_mae: 0.1268
Epoch 51/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 15s 5ms/step - loss: 0.0320 - mae: 0.1303 - val_loss: 0.0318 - val_mae: 0.1295
Epoch 52/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 16s 5ms/step - loss: 0.0321 - mae: 0.1303 - val_loss: 0.0304 - val_mae: 0.1270
Epoch 53/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0320 - mae: 0.1302 - val_loss: 0.0311 - val_mae: 0.1262
Epoch 54/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0322 - mae: 0.1303 - val_loss: 0.0336 - val_mae: 0.1268
Epoch 55/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0319 - mae: 0.1301 - val_loss: 0.0308 - val_mae: 0.1264
Epoch 56/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0322 - mae: 0.1303 - val_loss: 0.0306 - val_mae: 0.1261
Epoch 57/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0320 - mae: 0.1301 - val_loss: 0.0307 - val_mae: 0.1267
Epoch 58/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0322 - mae: 0.1303 - val_loss: 0.0307 - val_mae: 0.1259
Epoch 59/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0319 - mae: 0.1299 - val_loss: 0.0303 - val_mae: 0.1256
Epoch 60/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0320 - mae: 0.1299 - val_loss: 0.0325 - val_mae: 0.1265
Epoch 61/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0320 - mae: 0.1300 - val_loss: 0.0309 - val_mae: 0.1276
Epoch 62/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1299 - val_loss: 0.0309 - val_mae: 0.1260
Epoch 63/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0321 - mae: 0.1300 - val_loss: 0.0305 - val_mae: 0.1263
Epoch 64/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1297 - val_loss: 0.0301 - val_mae: 0.1263
Epoch 65/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0321 - mae: 0.1298 - val_loss: 0.0304 - val_mae: 0.1283
Epoch 66/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0319 - mae: 0.1298 - val_loss: 0.0307 - val_mae: 0.1269
Epoch 67/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0318 - mae: 0.1297 - val_loss: 0.0323 - val_mae: 0.1274
Epoch 68/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0321 - mae: 0.1299 - val_loss: 0.0301 - val_mae: 0.1260
Epoch 69/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0320 - mae: 0.1299 - val_loss: 0.0301 - val_mae: 0.1258
Epoch 70/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 0.0320 - mae: 0.1298 - val_loss: 0.0305 - val_mae: 0.1255
Epoch 71/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0321 - mae: 0.1298 - val_loss: 0.0319 - val_mae: 0.1265
Epoch 72/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0320 - mae: 0.1297 - val_loss: 0.0314 - val_mae: 0.1256
Epoch 73/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1297 - val_loss: 0.0316 - val_mae: 0.1269
Epoch 74/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0318 - mae: 0.1295 - val_loss: 0.0308 - val_mae: 0.1273
Epoch 75/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0319 - mae: 0.1298 - val_loss: 0.0327 - val_mae: 0.1256
Epoch 76/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0320 - mae: 0.1298 - val_loss: 0.0303 - val_mae: 0.1265
Epoch 77/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1296 - val_loss: 0.0370 - val_mae: 0.1268
Epoch 78/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0320 - mae: 0.1297 - val_loss: 0.0345 - val_mae: 0.1259
Epoch 79/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0322 - mae: 0.1298 - val_loss: 0.0303 - val_mae: 0.1257
Epoch 80/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1294 - val_loss: 0.0306 - val_mae: 0.1260
Epoch 81/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1295 - val_loss: 0.0307 - val_mae: 0.1266
Epoch 82/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1296 - val_loss: 0.0301 - val_mae: 0.1251
Epoch 83/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1294 - val_loss: 0.0303 - val_mae: 0.1258
Epoch 84/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1294 - val_loss: 0.0306 - val_mae: 0.1271
Epoch 85/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1294 - val_loss: 0.0315 - val_mae: 0.1276
Epoch 86/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1295 - val_loss: 0.0307 - val_mae: 0.1259
Epoch 87/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1292 - val_loss: 0.0333 - val_mae: 0.1260
Epoch 88/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1294 - val_loss: 0.0513 - val_mae: 0.1267
Epoch 89/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1295 - val_loss: 0.0316 - val_mae: 0.1263
Epoch 90/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0317 - mae: 0.1293 - val_loss: 0.0306 - val_mae: 0.1252
Epoch 91/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0316 - mae: 0.1292 - val_loss: 0.0336 - val_mae: 0.1266
Epoch 92/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 0.0317 - mae: 0.1293 - val_loss: 0.0345 - val_mae: 0.1270
Epoch 93/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 0.0317 - mae: 0.1293 - val_loss: 0.0305 - val_mae: 0.1256
Epoch 94/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0317 - mae: 0.1292 - val_loss: 0.0315 - val_mae: 0.1256
Epoch 95/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0317 - mae: 0.1292 - val_loss: 0.0322 - val_mae: 0.1264
Epoch 96/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1291 - val_loss: 0.0318 - val_mae: 0.1280
Epoch 97/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1290 - val_loss: 0.0329 - val_mae: 0.1267
Epoch 98/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - loss: 0.0318 - mae: 0.1293 - val_loss: 0.0305 - val_mae: 0.1259
Epoch 99/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1291 - val_loss: 0.0347 - val_mae: 0.1260
Epoch 100/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1290 - val_loss: 0.0314 - val_mae: 0.1270
Epoch 101/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0319 - mae: 0.1293 - val_loss: 0.0319 - val_mae: 0.1267
Epoch 102/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1290 - val_loss: 0.0317 - val_mae: 0.1266
Epoch 103/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1292 - val_loss: 0.0319 - val_mae: 0.1261
Epoch 104/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1290 - val_loss: 0.0313 - val_mae: 0.1276
Epoch 105/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1292 - val_loss: 0.0315 - val_mae: 0.1269
Epoch 106/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0317 - mae: 0.1291 - val_loss: 0.0302 - val_mae: 0.1254
Epoch 107/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0318 - mae: 0.1291 - val_loss: 0.0331 - val_mae: 0.1266
Epoch 108/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0316 - mae: 0.1290 - val_loss: 0.0426 - val_mae: 0.1265
Epoch 109/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1290 - val_loss: 0.0302 - val_mae: 0.1256
Epoch 110/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1289 - val_loss: 0.0302 - val_mae: 0.1257
Epoch 111/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1289 - val_loss: 0.0402 - val_mae: 0.1272
Epoch 112/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0317 - mae: 0.1290 - val_loss: 0.0305 - val_mae: 0.1253
Epoch 113/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1287 - val_loss: 0.0307 - val_mae: 0.1267
Epoch 114/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0316 - mae: 0.1289 - val_loss: 0.0301 - val_mae: 0.1264
Epoch 115/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 0.0316 - mae: 0.1290 - val_loss: 0.0307 - val_mae: 0.1258
Epoch 116/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0316 - mae: 0.1288 - val_loss: 0.0318 - val_mae: 0.1299
Epoch 117/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 0.0314 - mae: 0.1286 - val_loss: 0.0308 - val_mae: 0.1271
Epoch 118/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0314 - mae: 0.1286 - val_loss: 0.0298 - val_mae: 0.1251
Epoch 119/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0316 - mae: 0.1287 - val_loss: 0.0317 - val_mae: 0.1277
Epoch 120/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0316 - mae: 0.1286 - val_loss: 0.0315 - val_mae: 0.1266
Epoch 121/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0317 - val_mae: 0.1282
Epoch 122/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0314 - mae: 0.1287 - val_loss: 0.0311 - val_mae: 0.1278
Epoch 123/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1286 - val_loss: 0.0329 - val_mae: 0.1271
Epoch 124/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1288 - val_loss: 0.0315 - val_mae: 0.1268
Epoch 125/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1287 - val_loss: 0.0320 - val_mae: 0.1285
Epoch 126/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1287 - val_loss: 0.0379 - val_mae: 0.1302
Epoch 127/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0351 - val_mae: 0.1263
Epoch 128/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0313 - mae: 0.1285 - val_loss: 0.0317 - val_mae: 0.1267
Epoch 129/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1285 - val_loss: 0.0404 - val_mae: 0.1285
Epoch 130/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0316 - mae: 0.1287 - val_loss: 0.0365 - val_mae: 0.1285
Epoch 131/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1288 - val_loss: 0.0299 - val_mae: 0.1252
Epoch 132/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0322 - val_mae: 0.1278
Epoch 133/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0304 - val_mae: 0.1265
Epoch 134/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0315 - mae: 0.1288 - val_loss: 0.0312 - val_mae: 0.1278
Epoch 135/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0313 - mae: 0.1285 - val_loss: 0.0301 - val_mae: 0.1255
Epoch 136/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0318 - val_mae: 0.1272
Epoch 137/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0313 - mae: 0.1285 - val_loss: 0.0301 - val_mae: 0.1262
Epoch 138/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0314 - mae: 0.1286 - val_loss: 0.0300 - val_mae: 0.1255
Epoch 139/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0314 - val_mae: 0.1263
Epoch 140/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0323 - val_mae: 0.1305
Epoch 141/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0300 - val_mae: 0.1252
Epoch 142/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 14s 4ms/step - loss: 0.0313 - mae: 0.1284 - val_loss: 0.0347 - val_mae: 0.1267
Epoch 143/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0309 - val_mae: 0.1274
Epoch 144/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0317 - mae: 0.1286 - val_loss: 0.0426 - val_mae: 0.1289
Epoch 145/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0320 - val_mae: 0.1272
Epoch 146/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0313 - mae: 0.1284 - val_loss: 0.0308 - val_mae: 0.1265
Epoch 147/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0324 - val_mae: 0.1298
Epoch 148/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0304 - val_mae: 0.1266
Epoch 149/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1287 - val_loss: 0.0307 - val_mae: 0.1263
Epoch 150/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0324 - val_mae: 0.1257
Epoch 151/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0322 - val_mae: 0.1311
Epoch 152/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1286 - val_loss: 0.0307 - val_mae: 0.1277
Epoch 153/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0314 - val_mae: 0.1285
Epoch 154/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0315 - mae: 0.1286 - val_loss: 0.0304 - val_mae: 0.1262
Epoch 155/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0323 - val_mae: 0.1308
Epoch 156/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0309 - val_mae: 0.1269
Epoch 157/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - loss: 0.0315 - mae: 0.1284 - val_loss: 0.0377 - val_mae: 0.1308
Epoch 158/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - loss: 0.0315 - mae: 0.1285 - val_loss: 0.0315 - val_mae: 0.1282
Epoch 159/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0313 - val_mae: 0.1287
Epoch 160/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 13s 4ms/step - loss: 0.0314 - mae: 0.1284 - val_loss: 0.0325 - val_mae: 0.1305
Epoch 161/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 0.0312 - mae: 0.1282 - val_loss: 0.0321 - val_mae: 0.1292
Epoch 162/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0314 - mae: 0.1285 - val_loss: 0.0311 - val_mae: 0.1271
Epoch 163/500
3179/3179 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 0.0313 - mae: 0.1283 - val_loss: 0.0303 - val_mae: 0.1273

In [65]:
# 예측하기
from sklearn.metrics import r2_score

y_pred_log = model.predict(x_test_scaled)

y_pred = np.expm1(y_pred_log.flatten())
y_test = np.expm1(y_test)

r2_score(y_test, y_pred)

6358/6358 ━━━━━━━━━━━━━━━━━━━━ 3s 517us/step

0.8682365999921466